
bundle:
    dependencies:
        - rock
        - rock.dfki
          #        - rock_ugv_nav

log:
    filter_backtraces: false
    events: true

    # logging Roby into file: logs/<date>/<file>.txt
    levels:
        roby/execution_engine: INFO
        #        syskit: DEBUG:debug.txt
        #syskit/models: DEBUG
        #syskit/instance_requirements: DEBUG
        #syskit/network_generation: DEBUG
        #syskit/network_generation/merge_solver: DEBUG
        #syskit/network_generation/engine: DEBUG
        #syskit/component: DEBUG
