#! /usr/bin/env ruby

require 'roby'
require 'syskit'
require 'Qt'
require 'metaruby/gui/html/page'
require 'syskit/gui/page'
require 'syskit/gui/component_network_view'

Roby.app.robot 'avalon_simulation'
Roby.app.using_plugins 'syskit'
Syskit.conf.only_load_models = true
Syskit.conf.disables_local_process_server = true
app = Qt::Application.new(ARGV)

Syskit.conf.disable_logging
Syskit.conf.disable_conf_logging

GUI = true

if GUI
    display = Qt::WebView.new
    display.show
    page = MetaRuby::GUI::HTML::Page.new(display.page)
    rendering = Syskit::GUI::ComponentNetworkView.new(page)
end

def update(plan, requirement_tasks)
    engine = Syskit::NetworkGeneration::Engine.new(plan)
    engine.resolve(:requirement_tasks => requirement_tasks)
end

def precompute(plan,requirement_tasks)
    engine = Syskit::NetworkGeneration::Engine.new(plan)
    engine.precompute(:requirement_tasks => requirement_tasks)
end

begin
    Roby.app.setup
    passes = Array.new
    passes << [Main.joystick_dev.to_instance_requirements]
    passes << [Main.target_move_def.to_instance_requirements,Main.joystick_dev.to_instance_requirements]
    passes << [Main.wall_right_def.to_instance_requirements,Main.joystick_dev.to_instance_requirements]
    #passes << [Main.bottom_cam_def.to_instance_requirements,Main.joystick_dev.to_instance_requirements]
    #passes << [Main.target_move_def.to_instance_requirements,Main.joystick_dev.to_instance_requirements]

    plan = rendering.plan
    passes.each_with_index do |requirements, idx|
        requirement_tasks = requirements.map do |req|
            plan.add_mission(task = req.as_plan)
            task.planning_task
        end

        precompute(plan, requirement_tasks)
#        plan.static_garbage_collect do |task|
#            plan.remove_object(task)
#        end

        update(plan, requirement_tasks)
        plan.static_garbage_collect do |task|
            plan.remove_object(task)
        end

        requirement_tasks.each do |t|
            plan.unmark_mission t.planned_task
        end
        rendering.render_plan(:id => idx.to_s)
    end
ensure Roby.app.cleanup
end

app.exec

