--- name:default
camera_image_width: 251
camera_image_height: 231
detection_threshold: 0.45
iir_size: 10
fixed_depth_near: -1.3
fixed_depth_far: -2.3
stereoCamMode: false
AsvHullWidth: 0.08
AsvLength: 1.0
AsvWidth: 1.0
