--- name:default
# reference depth far
fixed_depth: -1.1
# distance to keep while following
follow_dist: 5.0
# In degree. If we are heading towards the asv with a delte less then heading_threshold, we start moving
heading_threshold: 3.0
# Angle threshold in degree
iir_angle_threshold: 10.0
# Range Threshold in meters
iir_range_threshold: 2.0
# Don't move is the delta of desired and actual distance is smaller than motion_threshold
motion_threshold: 0.8
# Range Threshold in meters
not_detected_delay: 20
# The factor for the motion commands in x and y direction (1.0 is same as distance in meters)
speed: 1.0
# How many seconds the movement command must be near zero to change to standing state
standDuration: 10
# distance for surfacing
surface_dist: 2.0
