--- name:default
camera_image_width: 2592
camera_image_height: 1944
shadow_threshold: 0.02
shadow_sectors: 5
fixed_depth_near: -2.0
fixed_depth_far: -3.0
stereoCamMode: true
asvHullWidth: 0.35
asvLength: 4.0
asvWidth: 1.96
--- name:simulation
camera_image_width: 251
camera_image_height: 231
shadow_threshold: 0.02
shadow_sectors: 5
fixed_depth_near: -2.0
fixed_depth_far: -3.0
stereoCamMode: false
asvHullWidth: 0.08
asvLength: 1.0
asvWidth: 1.0
