--- name:default
# If true, the component will send a zero command before getting into an
# exception state. Otherwise, it will not do anything
keep_position_on_exception: true
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# This property defines the timeout for the cascade input port in seconds. 0
# means that the timeout would be ignored.
timeout_cascade: 1.0
# This property defines the timeout for the cmd_in input port in seconds. 0
# means that the timeout would be ignored.
timeout_in: 1.0

--- name:all
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - true
  - true
  - true
  angular:
  - true
  - true
  - true

--- name:z_roll_pitch_yaw
# This property defines which parts of the command input is expected to be
# set once we merged all the declared input ports.
expected_inputs:
  linear:
  - false
  - false
  - true
  angular:
  - true
  - true
  - true
