--- name:default
# in ms
constantInterval: 500
# 0=no interval (manually switching), 1=constant interval, 2=random interval
interval_mode: 2
# in ms
randomInterval_max: 3000
# in ms
randomInterval_min: 500
