--- name:default
# defaults to unset, so not taken into account
final_heading: .nan
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# no documentation available for this property
step_width: 3.0
# no documentation available for this property
timeout_at_end_before_mark_end_reached: 10.0
# no documentation available for this property
trajectory:
  speed: 0.0
  spline:
    geometric_resolution: 0.1
    dimension: 3
    curve_order: 3
    kind: :DEGENERATE
    knots: []
    vertices: []
# use the zero heading for debuggin, instead calculated heading
use_zero_heading: false
