--- name:sonar
  rightlimit: 3999
  leftlimit: 1
  cont: 1
--- name:narrow_front
# Special sonar settings for wall following. Front Sonar.
  rightlimit: 3999
  leftlimit: 2399
  cont: 1
--- name:narrow_right
  rightlimit: 5599
  leftlimit: 3999
  cont: 1
