--- name:default
# Maximum allowed Value between 0 and 1 that is an cutoff for maximum pwm value 0.8 means 80% PWM
#cutoff: 
#     - 0.0 ###LOGGING IST AUCH AUS
#     - 0.0
#     - 0.0
#     - 0.0
#     - 0.0
#     - 0.0
cutoff: 
  - 0.8
  - 0.8
  - 0.8
  - 0.8
  - 0.8
  - 0.8
# no documentation available for this property
heading_pid: 
  max: 0.6
  d:  0 #-0.3
  p: -0.5
  min: -0.6
  i: 0.0
# no documentation available for this property
pitch_pid: 
  max: 1.0
  d: -0.8
  p: -2.0 #2.0
  min: -1.0
  i: -0.2
# no documentation available for this property
pitch_target: 0.0  #0.122173047639603
# no documentation available for this property
timeout: 20.0
# no documentation available for this property
x_factor: 0.6
# no documentation available for this property
y_coupling_factor: -0.05
# no documentation available for this property
y_factor: 1.0
# no documentation available for this property
z_coupling_factor: -0.19
# no documentation available for this property
z_pid: 
  max: 0.7
  d: 0.0 #0.1
  p: 2.0
  min: -0.7
  i: 0.02
use_min_ground_distance: true 
min_ground_distance: 0.6
joint_names: ["yaw","dive","right","left","pitch","strave"]
--- name:simulation
z_coupling_factor: 0.0
y_coupling_factor: 0.0
pitch_target: 0.0
x_factor: 1.0
timeout: 0.0
y_factor: 3.0
pitch_pid:
  p: 0.1
  i: 0.0
  d: 0.0
heading_pid:
  i: 0.0
  p: -0.5
z_pid:
  p: 1.0
  i: 0.1
cutoff: 
  - 1.0 
  - 1.0 
  - 1.0 
  - 1.0 
  - 1.0 
  - 1.0 
use_min_ground_distance: false 
min_ground_distance: 0.2
