--- name:default
# start the simulation graphical interface with this module
enable_gui: 1
# scenefile of the robot module, which should be loaded
with_manipulator_gui: 1

# Initial position - complete mission
initial_x: 0.0
initial_y: 0.0
initial_z: 0.0
initial_yaw: 0.0

# Initial position - gate
# initial_position:
#     data: [48, 0, -2]
# initial_yaw: 0
