--- name:default
# no documentation available for this property
optimal_heading_distance: 999.0
timeout: 1.0
# no documentation available for this property
x_pid: 
  max: 1
  d: 0.0
  p: 0.2
  min: -1
  i: 0.0
# no documentation available for this property
y_pid: 
  max: 1
  d: 0.0
  p: 0.5
  min: -1
  i: 0.0
