--- name:default_rear
left_limit: 2.2
right_limit: 0.95
resolution: 0.1
maximum_distance: 50.0
ping_pong_mode: true
--- name:sonar_rear_ground
left_limit: 1.96349540849362
right_limit: 1.17809724509617
ping_pong_mode: true
--- name:sonar_rear_right
left_limit: 0.094
right_limit: -0.094
ping_pong_mode: true
--- name:straight_rear
left_limit: 0.0
right_limit: -0.2
ping_pong_mode: true

