--- name:default
# no documentation available for this property
timeout: 1.0
# no documentation available for this property
x_pid: 
  max: 1
  d: 0.0
  p: 0.1
  min: -1
  i: 0.0
# no documentation available for this property
y_pid: 
  max: 1
  d: 0.0
  p: 0.1
  min: -1
  i: 0.0
