--- name:default
start_angle: 3.141592654
end_angle: -3.141592654
resolution: 0.1
maximum_distance: 50.0
ping_pong_mode: false
--- name:wall_servoing
start_angle: 0.78
end_angle: -0.78
ping_pong_mode: true
--- name:distance_estimation
start_angle: 0.01
end_angle: -0.01
ping_pong_mode: true

