--- name:buoydetector
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 10
# set high hue value to reduce color space
hue_high: 200
# set low hue value to recude color space
hue_low: 56
# maximum buoy distance in m
max_buoy_distance: 0.5
