--- name:default
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 10
# maximum buoy distance in m
max_buoy_distance: 1.5
buoy_radius: 0.10
houghTh: 25
hValue: 55
vValue: 40
sValue: 70
steps: 5
edgeTh: 35
run_in_simulation: 0
debug_gui: false
buoy_depth: -1.8
good_y_z: 0.2
good_x: 0.3
filter_timeout: 1.5
strafe_intensity: -0.5
maxX: 0.2
headingModulation: 0.0
headingFactor: 4.0
cutting_time: 14
cutting_hight: 0.25
