--- name:default
lost_timeout: 15
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 10
# maximum buoy distance in m
max_buoy_distance: 0.55
buoy_radius: 0.05
houghTh: 10
hValue: 60
vValue: 40
sValue: 175
steps: 5
edgeTh: 35
run_in_simulation: 0
debug_gui: false
buoy_depth: 1.45
good_y_z: 0.2
good_x: 0.3
filter_timeout: 2.0 
strafe_intensity: -0.5
maxX: 0.2
headingModulation: 0.0
headingFactor: 4.0
cutting_time: 3
cutting_hight: -0.25
