--- name:default
width: 648
height: 468
fps: 5
whitebalance_mode: 'auto'
gain: 18
exposure: 100
trigger_mode: 'fixed'
binning: 4
output_format: 'rgb3'

--- name:left_unicap_camera
camera_id: 1

--- name:right_unicap_camera
camera_id: 2
