--- name:default
# no documentation available for this property
maxRotationSpeed: 3.14
# no documentation available for this property
maxSpeed: 1.5
# no documentation available for this property
minSpeed: 0.1
