--- name:default
# no documentation available for this property
can_id: 0x440
# no documentation available for this property
externalPressureFactor: 1600000.0
# no documentation available for this property
filter_param_external_pressure: 8
# no documentation available for this property
filter_param_internal_pressure: 4
# no documentation available for this property
filter_param_temperature: 4
# no documentation available for this property
filter_param_water: 4
# no documentation available for this property
internalPressureFactor: 152166.666666667
# no documentation available for this property
internalPressureOffset: 10555.555555556
# no documentation available for this property
temperatureFactor: 330.0
# no documentation available for this property
temperatureOffset: -60.0
#smoothing depth and depth velocity
smooth_factor: 0.7
