--- name:default
# hostname where the gps daemon is running
hostname: localhost
# Origin in UTM coordinates, that is used for position readings.
origin: 
  data: 
  - 569257 
  - 4882858 
  - 0.0 
# UTM north for conversion of WGS84 to UTM
utm_north: 1
# UTM zone for conversion of WGS84 to UTM
utm_zone: 32

## Transformer config
# use transformation provided by the transformer instead of the origin property.
use_transformer: true
# the global name that should be used for the internal gps_utm_zone frame
gps_utm_zone_frame: world_utm_sauce
# the global name that should be used for the internal map frame
map_frame: map_sauce
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
