--- name:default
# Timeout for io operations
comTimeout:
  microseconds: 500000 
# Configuration for all hbridges (initial values)
configuration:
  config:
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 0
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 10000
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 3000
    maxCurrentCount: 220
    timeout: 200
    pwmStepPerMs: 20
    controllerInputEncoder: :INTERNAL
  - maxPWM: 0 
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 0
    maxCurrentCount: 0
    timeout: 0
    pwmStepPerMs: 0
    controllerInputEncoder: :INTERNAL
  - maxPWM: 0
    openCircuit: 0
    maxMotorTemp: 0
    maxMotorTempCount: 0
    maxBoardTemp: 80
    maxBoardTempCount: 100
    maxCurrent: 0
    maxCurrentCount: 0
    timeout: 0
    pwmStepPerMs: 0
    controllerInputEncoder: :INTERNAL
# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []
