--- name:default
# Timeout for io operations
comTimeout:
  microseconds: 500000 
# Configuration for all hbridges (initial values)
configuration:
  - name: 'left'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
  - name: 'right'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
  - name: 'dive'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
  - name: 'pitch'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
  - name: 'strave'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
  - name: 'yaw'
    externalTempSensor: 0
    statusFrequency: 1
    encoder_config_intern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
    encoder_config_extern:
      ticksPerTurn: 0
      leapTickValue: 0
      tickDivider: 1
      ticksPerTurnDivided: 0
      zeroPosition: 0.0
      type: :ENCODER_NONE
# This parameter defines if the reader task should act as bus master.WARNING, only set this to !0 if there is no mainboard present in your system
isBusMaster: 0 
