--- name:default
# Timeout for io operations
comTimeout:
  microseconds: 1000000 
# Configuration for all hbridges (initial values)
configuration:
    - actuator:
        name: 'left'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 100
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
    - actuator:
        name: 'right'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 0
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
    - actuator:
        name: 'dive'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 100
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
    - actuator:
        name: 'pitch'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 100
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
    - actuator:
        name: 'strave'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 100
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
    - actuator:
        name: 'yaw'
        maxPWM: 10000
        openCircuit: 0
        maxMotorTemp: 0
        #maxMotorTempCount: 0
        maxBoardTemp: 80
        #maxBoardTempCount: 100
        maxCurrent: 3000
        maxCurrentCount: 220
        timeout: 8000
        pwmStepPerMs: 20
        controllerInputEncoder: :INTERNAL
# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []
