--- name:default
# no documentation available for this property
blur: 16 
# no documentation available for this property
hMax: 78
# no documentation available for this property
hMin: 18
# no documentation available for this property
sMax: 256
# no documentation available for this property
sMin: 0
# no documentation available for this property
steps_per_frame: 1
# no documentation available for this property
target_pixel_s: 70000
# no documentation available for this property
unsetValue: 0
# no documentation available for this property
vMax: 130 
# no documentation available for this property
vMin: 14
--- name:structure
blur: 0
hMax: 253
hMin: 16 
maxVadapt: 255 
minVadapt: 0 
sMax: 251
sMin: 4
steps_per_frame: 0 
target_pixel_s: 100
unsetValue: 0
vMax: 62
vMin: 30 
