--- name:default
# start the simulation graphical interface with this module
initial_scenes: 
    - "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/simulation/orogen/avalon_simulation/configuration/floor_large.scn"
    - "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/simulation/orogen/avalon_simulation/configuration/walls.scene"
    - "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/simulation/orogen/avalon_simulation/configuration/avalon_objects.scn"
    - "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/simulation/orogen/avalon_simulation/configuration/assambly.scn"
    - "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/simulation/orogen/avalon_simulation/configuration/fog.scene"
enable_gui: 1
#use_osg_ocean: 0
#debug_sonar: 1
# scenefile of the robot module, which should be loaded
#with_manipulator_gui: 1
reaction_to_physics_error: "warn"
use_now_instead_of_sim_time: true
start_sim: true 
realtime_calc: true
gravity: 
  data:
  - 0 
  - 0 
  - 0
positions:
- nodename: 'Cylinder' #The pipeline
  posx: -80
  posy: 50
  posz: -20
  rotx: 0 
  roty: 0
  rotz: 0
- nodename: 'assambly' #Der pipeline-tannenbaum
  posx: -21
  posy: 26
  posz: -8
  rotx: 0 
  roty: 0
  rotz: 0
- nodename: 'avalon' #This is a really fancy thing
  posx: -20.0
  posy: 2.5
  posz: 0
  rotx: 0 
  roty: 0
  rotz: 90.0
- nodename: 'BuoyWall'
  posx: -2.0
  posy: 40
  posz: 0
  rotx: 0 
  roty: 0
  rotz: 90.0
- nodename: 'BuoyGate1'
  posx: -10.0
  posy: 25.0
  posz: 0
  rotx: 0 
  roty: 0
  rotz: 90.0
- nodename: 'BuoyGate2'
  posx: -10.0
  posy: 27.0
  posz: 0
  rotx: 0 
  roty: 0
  rotz: 90.0
