--- name:default
# no documentation available for this property
amount_of_actuators: 6
# no documentation available for this property
maximum_thruster_force:
- 20.0
- 20.0
- 20.0
- 20.0
- 20.0
- 20.0
# no documentation available for this property
node_name: avalon
# no documentation available for this property
thruster_direction:
#Rear Vertical
- data: [0, 0, 1]    #Rear Vertical
- data: [0, 0, -1]     #Middle Vertical
- data: [1, 0, 0]    #Right
- data: [1, 0, 0]    #Left
- data: [0, -1, 0]     #Rear Horizotal
- data: [0, 1, 0]    #Middle Horizontal
thruster_position:
- data: [-0.5955, 0, 0]       #Rear Vertical
- data: [0, 0, 0]             #Middle Vertical
- data: [0, -0.157, 0]        #Right
- data: [0, 0.157, 0]        #Left
- data: [-0.688, 0.082, 0]    #Rear Horizontal
- data: [0, 0, 0]             #Middle Horizontal
