--- name:default
# maximum distance for sonar responses in a beam
beam_threshold_max: 14.0
# minimum distance for sonar responses in a beam
beam_threshold_min: 1.0
# if set to true the threshold for the sonar beams is enabled
enable_beam_threshold: 1
# reference depth
fixed_depth: -1.4
# modulates the heading to the wall with a fixed degree, default is 0 than the wall in in front
heading_modulation: 0.0
# minimum value for responses in a beam, everything below will be ignored
min_response_value: 30.0
# reference distance to wall
wall_distance: 2.0
# end angle for the wall estimation
wall_estimation_end_angle: -1
# start angle for the wall estimation
wall_estimation_start_angle: -1
# set distance for the y axis, witch will result in a certain speed
servoing_speed: 0.0
# the exploration will simply drive forward in the origin serviong direction
exploration_speed: 0
# maximal inlier distance to the model
wall_estimation_ransac_threshold:  0.4
# minimum count inliers of the point cloud in percent to be a valid model
wall_estimation_ransac_min_inliers: 0.6

--- name:distance_estimator
servoing_speed: 0
heading_modulation: 0

--- name:wall_approach
servoing_speed: 0
heading_modulation: 0
wall_distance: 2.0

--- name:approach_buoy
servoing_speed: 0.2
# +pi/2
heading_modulation: 1.57
# reference distance to wall
wall_distance: 4.0

--- name:drive_left
servoing_speed: 0.7
# +pi/8
heading_modulation: 0.0
# reference distance to wall
wall_distance: 2.5

--- name:servo_right_wall
servoing_speed: 0.2
# +pi/2
heading_modulation: 1.57
# reference distance to wall
wall_distance: 2.0

