### front sonar config
--- name:default
# Configuration for Sonar
config: 
  left_limit: 
    rad: 0.01 #3.141592653589793
  right_limit: 
    rad: -0.01 #3.141592653589793
  angular_resolution: 
    rad: 0.08726646259971647
  max_distance: 8.0
  min_distance: 0.25
  resolution: 0.1
  speed_of_sound: 1500.0
  gain: 0.2
  low_resolution: 0
  continous: 0
# the device port
port: /dev/ttyS7
# read_timeout
read_timeout: 0.5
# timeout for writing to the serial port in seconds
write_timeout: 0.1
# timeout for configuring the device in seconds
configure_timeout: 10.0
# timeout for the dst micron dst echo sounder. Set it to 0 if none is connected
echo_sounder_timeout: 0.0
--- name:studiobad
config:
  continous: 1
  gain: 0.5
  max_distance: 15.0
  resolution: 0.1
port: /dev/ttyS7
--- name:wall_servoing_front
config:
  continous: 0
  gain: 0.2
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 1.01
  right_limit:
    rad: -1.01
port: /dev/ttyS7
--- name:wall_servoing_left
config:
  continous: 0
  gain: 0.2
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 2.67
  right_limit:
    rad: 0.0
port: /dev/ttyS7
--- name:wall_servoing_right
config:
  continous: 0
  gain: 0.2
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 0.0
  right_limit:
    rad: -2.67
port: /dev/ttyS7
--- name:dual_wall_servoing
config:
  continous: 0
  gain: 0.2
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 0.094 #0.03 * PI
  right_limit:
    rad: -1.67 #-0.53 * PI
port: /dev/ttyS7
--- name:straight_front
config:
  continous: 0
  gain: 0.2
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 0.05
  right_limit:
    rad: -0.05
port: /dev/ttyS7

### rear sonar config
--- name:default_rear
# Configuration for Sonar
config: 
  left_limit: 
    rad: 3.141592653589793
  right_limit: 
    rad: 3.141592653589793
  angular_resolution: 
    rad: 0.08726646259971647
  max_distance: 15.0
  min_distance: 0.25
  resolution: 0.1
  speed_of_sound: 1500.0
  gain: 0.2
  low_resolution: 0
  continous: 1
# the device port
port: /dev/ttyS5
# read_timeout
read_timeout: 0.5
# timeout for writing to the serial port in seconds
write_timeout: 0.1
# timeout for configuring the device in seconds
configure_timeout: 10.0
# timeout for the dst micron dst echo sounder. Set it to 0 if none is connected
echo_sounder_timeout: 0.5
--- name:sonar_rear_ground
config: 
  continous: 0
  max_distance: 20.0
  resolution: 0.1
  left_limit:
    rad: 1.96349540849362
    #(90.0+22.5)/180.0*Math::PI
  right_limit:
    rad: 1.17809724509617
    #(90.0-22.5)/180.0*Math::PI
port: /dev/ttyS5
--- name:sonar_rear_right
config:
  gain: 0.2 
  continous: 0
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 0.094 #0.03 * PI
  right_limit:
    rad: -0.094 #-0.03 * PI
port: /dev/ttyS5
--- name:straight_rear
config:
  gain: 0.2
  continous: 0
  max_distance: 10.0
  resolution: 0.1
  left_limit:
    rad: 0.0
  right_limit:
    rad: -0.2
port: /dev/ttyS5

