--- name:default
# Configuration Values for Sonar
config: 
  stamp: 
    microseconds: 0
  adc8on: 1
  cont: 1
  scanright: 0
  invert: 0
  chan2: 1
  applyoffset: 0
  pingpong: 0
  rangeScale: 30
  leftLimit: 
    rad: 3.141592653589793
  rightLimit: 
    rad: 3.141592653589793
  adSpan: 81
  adLow: 8
  initialGain: 0.2 
  motorStepDelayTime: 25
  motorStepAngleSize: 
    rad: 0.08726646259971647
  maximumDistance: 15.0
  resolution: 0.1
  adcSetpointCh: 0
port: /dev/ttyF3
timeout: 200
--- name:studiobad
config:
  cont: 1
  initialGain: 0.5
  maximumDistance: 15.0
  resolution: 0.1
port: /dev/ttyF3
--- name:sonar_rear
config: 
  cont: 0
  maximumDistance: 20.0
  resolution: 0.1
  leftLimit:
    rad: 1.96349540849362
    #(90.0+22.5)/180.0*Math::PI
  rightLimit:
    rad: 1.17809724509617
    #(90.0-22.5)/180.0*Math::PI
port: /dev/ttyF1
--- name:wall_servoing
config:
  cont: 0
  pingpong: 1
  initialGain: 0.5
  maximumDistance: 10.0
  resolution: 0.1
  leftLimit:
    rad: 1.01
  rightLimit:
    rad: -1.01
port: /dev/ttyF3
--- name:distance_estimation
config:
  cont: 0
  pingpong: 1
  maximumDistance: 20.0
  leftLimit:
    rad: 0.01
  rightLimit:
    rad: -0.01
port: /dev/ttyF3

