--- name:default
# Configuration Values for Sonar
config: 
  stamp: 
    microseconds: 0
  adc8on: 1
  cont: 1
  scanright: 0
  invert: 0
  chan2: 1
  applyoffset: 0
  pingpong: 0
  rangeScale: 30
  leftLimit: 1
  rightLimit: 6399
  adSpan: 81
  adLow: 8
  initialGain: 50
  motorStepDelayTime: 25
  motorStepAngleSize: 32
  adInterval: 30
  numberOfBins: 300
  adcSetpointCh: 0
# the device port
port: /dev/ttyS3
# timeout on the distance readings in milliseconds
timeout: 200
--- name:sonar_rear
config: 
  leftLimit: 1200
  rightLimit: 2000
port: /dev/ttyUSB0
