--- name:default
# maximum distance for sonar responses in a beam
beam_threshold_max: 15.0
# minimum distance for sonar responses in a beam
beam_threshold_min: 2.0
# print debug output
debug_output: 0
# if set to true the threshold for the sonar beams is enabled
enable_beam_threshold: 1
# reference depth
fixed_depth: -1.5
# modulates the heading to the wall with a fixed degree, default is 0 than the wall in in front
heading_modulation: 0.0
# minimum value for responses in a beam, everything below will be ignored
min_response_value: 30.0
# reference distance to wall
wall_distance: 3.0
# end angle for the wall estimation
wall_estimation_end_angle: 3.93
# start angle for the wall estimation
wall_estimation_start_angle: 2.36
# set distance for the y axis, witch will result in a certain speed
servoing_speed: 0.0
# the exploration will simply drive forward in the origin serviong direction
exploration_speed: 0.2
# maximal inlier distance to the model
wall_estimation_ransac_threshold:  0.4
# minimum count inliers of the point cloud in percent to be a valid model
wall_estimation_ransac_min_inliers: 0.6

--- name:drive-left
servoing_speed: 0.9
heading_modulation: 0

--- name:drive-right
servoing_speed: -0.9
heading_modulation: 0

--- name:follow-right-wall
servoing_speed: 0.3
heading_modulation: 1.5707 #pi/2
wall_estimation_start_angle: 0.799
wall_estimation_end_angle: 2.399

