## CENTER: 3200
#    800  is 45 degrees
#    1600 is 90 degrees
#    1600: full left
#    4800: full right
#    6399/0: full behind
--- name:sonar_rear
# Configuration Values for Sonar
config: 
  rightLimit: 6399
  adInterval: 30
  motorStepAngleSize: 32
  pingpong: 0
  adc8on: 1
  adSpan: 81
  rangeScale: 30
  chan2: 1
  numberOfBins: 300
  applyoffset: 0
  invert: 0
  initialGain: 50
  motorStepDelayTime: 25
  adLow: 8
  cont: 1
  stamp: 
    microseconds: 0
  leftLimit: 1
  scanright: 0
  adcSetpointCh: 0
# the device port
port: /dev/ttyUSB0
# timeout on the distance readings in milliseconds
timeout: 200
--- name:sonar
# Configuration Values for Sonar
config: 
  rightLimit: 3999
  adInterval: 200
  motorStepAngleSize: 32
  pingpong: 1
  adc8on: 1
  adSpan: 81
  rangeScale: 30
  chan2: 1
  numberOfBins: 600
  applyoffset: 0
  invert: 0
  initialGain: 230
  motorStepDelayTime: 25
  adLow: 8
  cont: true
  stamp: 
    microseconds: 0
  leftLimit: 1
  scanright: 0
  adcSetpointCh: 0
# the device port
port: /dev/ttyS3
# timeout on the distance readings in milliseconds
timeout: 200
--- name:narrow_front
# (wall servoing): Used in drive_left
# Special sonar settings for wall following. Front Sonar.
config:
  leftLimit: 2300
  rightLimit: 4000
  cont: 0
  pingpong: 1
  adInterval: 100
  numberOfBins: 300
  initialGain: 100
  motorStepDelayTime: 12
--- name:wall_approach
# (wall servoing): Used in distance_estimator
# Special sonar settings to approach the wall
config:
  leftLimit: 3100
  rightLimit: 3300
  cont: 0
  pingpong: 1
  adInterval: 100
  numberOfBins: 300
  initialGain: 50
--- name:narrow_right
# (wall servoing): used in all the other modes (approach_buoy, servo_right_wall)
config:
  leftLimit: 4000
  rightLimit: 5600
  cont: 0
  pingpong: 1
  adInterval: 50
  numberOfBins: 300
  initialGain: 50
