--- name:default
# Configuration Values for Sonar
config: 
  config: 
    filterGainCh2: 1
    rightLimit: 3300
    V3BParams: 29
    maxAgeCh1: 107
    ctl2: 0
    filterGain: 1
    slopeDelayCh1: 0
    maxAgeCh2: 107
    stepSize: 8 
    rangeScale: 20
    txnch1: 77846282
    slopeDelayCh2: 0
    minorAxisDir: 1600
    slopeCh1: 110
    txnch2: 162403450
    slope_Ch1: 110
    PrfSpl: 0
    slopeCh2: 150
    headType: 5
    slope_Ch2: 150
    majorAxisPan: 1
    setPoint: 100
    maxAge: 107
    adThreashold: 50
    adThrCh1: 50
    motorTime: 25
    adThrCh2: 50
    lockout: 500
    PrfCtl2: 0
    txPulseLength: 30
    setPointCh1: 100
    rxnch1: 138915348
    setPointCh2: 100
    scanZ: 0
    leftLimit: 1600 
    rxnch2: 223472517
    headCtl: 9090
    filterGainCh1: 1
    scanTime: 30
  stamp: 
    microseconds: 0
# the device port
offset: 2.14
port: /dev/ttyS1
# timeout on the distance readings in milliseconds
timeout: 200
