--- name:default
# no documentation available for this property
fluidType: 0
# no documentation available for this property
gain: 2.0
# no documentation available for this property
hostname: '192.168.128.16'
# no documentation available for this property
imageRes: 4
# no documentation available for this property
maxRange: 30.0
# no documentation available for this property
minRange: 1.0
# no documentation available for this property
port: 1149
# no documentation available for this property
rangeRes: 0.0
# no documentation available for this property
soundSpeed: 1536
# no documentation available for this property
tvgSlope: 0.0
# no documentation available for this property
tx: 1
