--- name:default
# effective sample size threshold controls the resampling timing and uses values between 0.0 and 1.0 particles
effective_sample_size_threshold: 0.9
# initial centre position for all particles
init_position: []
# spatial covariance from initial centre position for initialization
init_variance: []
# Time in s the particle filter will wait for expected samples
max_sample_delay: 2.0
# minimum depth for collecting perception samples
minimum_depth: -0.0
# minimum number of perceptions before starting resampling
minimum_perceptions: 3
# ratio for generating new particles after each measurement
# hough_interspersal_ratio: 0.0
# number of used particles
particle_number: 20
# ignore velocity in speed samples for dynamic update
pure_random_motion: true
# automatic reset of particle filter after not receiving any perception for X seconds
reset_timeout: 10.0
# sets sonar covariance for defining measurement uncertainty
sonar_covariance: 2.0
# sets importance ratio for sonar perception updates
sonar_importance: 1.0
# set maximum distance for filtering sonar samples
sonar_maximum_distance: 20.0
# set maximum distance for filtering sonar samples
sonar_minimum_distance: 1.0
# sets a static covariance for speed samples
static_motion_covariance: [5.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0]
# start map for localization algorithm
yaml_map: ''
# yaw offset if reference heading is not constistent with current mission
yaw_offset: 0.0

