--- name:default
# enables the debug output port
enable_debug_output: 0
# the exploration will simply drive forward in the origin serviong direction
exploration_speed: 0.1
# fading out factor for the features in center wall estimator
fading_out_factor: 0.02
# epsilon in one meter distance of dbscan algorithm. epsilon will be increased linear by the distance of the features
dbscan_epsilon: 0.15
# reference depth
fixed_depth: -1.0
# modulates the heading to the wall with a fixed degree, default is 0 than the wall is in front
heading_modulation: 0.4
# the auv will move away from the wall if the wall is to near
minimal_wall_distance: 0.75
# set distance for the y axis, witch will result in a certain speed
servoing_speed: 0.5
# reference distance to wall
wall_distance: 3.0
# minimum count inliers of the point cloud in percent to be a valid model
wall_estimation_ransac_min_inliers: 0.85
# maximal inlier distance to the model
wall_estimation_ransac_threshold: 0.5
# start angle for the wall estimation
wall_estimation_start_angle: 1.01
# end angle for the wall estimation
wall_estimation_end_angle: -1.01
--- name:wall_left
heading_modulation: 0.4
servoing_speed: 0.5
wall_estimation_start_angle: 1.01
wall_estimation_end_angle: -0.785
--- name:wall_right
heading_modulation: -0.4
servoing_speed: -0.5
wall_estimation_start_angle: 0.785
wall_estimation_end_angle: -1.01
